language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - TEST=quick
  - TEST=slow
install: >
  pip install -r requirements.txt --use-mirrors &&
  sudo apt-get install redis-server &&
  sudo service redis-server start
script: >
  ./tests/travis/run.sh
